name: megan
favicon: null
layout_spectrum: 0.87996
typography_spectrum: 0.44313
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6ebf1'
    - '#f04a4c'
    - '#000000'
    - '#a22239'
    - '#5b6064'
  brandStrength: 0.875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
